[package]
name = "wrausmt"
version = "0.1.0"
authors = ["Jason LeBrun <jblebrun@gmail.com>"]
edition = "2018"

[build-dependencies]
"codegen" = { path = "codegen" }

[workspace]
members = ["codegen"]
