[package]
name = "wrausmt-runtime"
authors = ["Jason LeBrun <jblebrun@gmail.com>"]
version = "0.1.0"
edition = "2021"

[dependencies]
"codegen" = { workspace = true }

[build-dependencies]
"codegen" = { workspace = true }
